frontend-opensource-project/use-react-hooks

.commitlintrc
.gitignore
.gitmojirc.json
.husky/commit-msg
package-lock.json
package.json

- 작업명: Jira 이슈 별도의 git convention 설정
- 티켓: [티켓 제목](티켓 URL)
- 상태: 신규
- gitmoji를 포함한 git convention husky 설정
-
- gitmoji client 툴 추가로 인한 npm install 재실행 필요
- husky/commit-msg 성공시 아이콘  변경 (🔆->✅)
- [.commitlintrc] : 컨벤션 세부사항 변경
- [.gitmojirc.json] : 메시지 첫글자 소문자 변경을 위한 gitmoji client 툴 설정 파일 추가
- git add 후 `npx gitmoji -c`입력시, gitmoji와 커밋메시지를 입력할 수 있는 gitmoji client 툴 실행
- `<emoji> <type>: <message>` 형태로 작성 시 깃 메시지 컨벤션 통과
- https://woolen-music-b46.notion.site/c8561b8f6b7748a38b27bfc66a066ef4
-

🩹 chore: gitmoji를 포함한 git convention 설정

---

src/hooks/useDelayFlag.ts
src/types/number.ts

- 작업명: useDelayFlag
- 티켓: [[react hooks] useDelayFlag](https://use-react-hooks.atlassian.net/browse/URH-10)
- 상태: 신규
- 인자로 받은 플래그(페칭 또는 로딩)를 일정 시간 이상 지연시킵니다.
- 데이터 페칭 시간이 0.1초만에 종료될 경우 사용자에게 로딩 UI를 보여주면 플리커 현상이 발생하는데, 이를 개선할 수 있는 훅입니다.
- 이 훅을 통해 반환된 플래그는 기본적으로 1초(1000ms)간 지속됩니다.
```ts
const isDelayLoading = useDelayFlag(isLoading);
// or
const isTwoSecondDelayLoading = useDelayFlag(isLoading, 2000);
```

✨ feat: useDelayFlag 생성

---

jest.config.ts
jest.setup.ts
package-lock.json
package.json
src/hooks/useWindowSize.test.ts
src/hooks/useWindowSize.ts
tsconfig.spec.json

- 작업명: 테스트 환경 셋팅
- 티켓: [테스트환경 셋팅](https://use-react-hooks.atlassian.net/browse/URH-32?atlOrigin=eyJpIjoiNjkwYjFiZjVjYjQzNGM3ZGEyMDdhOGQ2ZDgxZGQ1MmQiLCJwIjoiaiJ9)
- 상태: 신규
- `jest.config.ts` : jest 기본 설정 파일
- `jest.setup.ts` : test 실행전 사전 실행되는 설정 파일
- `tsconfig.spec.json` : 테스트 환경을 설정하기 위한 config파일
- 개발환경에 다수의 추가사항이 있으니 npm i 필수로 실행해주세요
- 테스트코드 작성완료를 위해 `src/hooks/useWindowSize.ts`에서 저번에 커밋되지 못한 delayTime 0 포함 조건이 이번에 함께 수정되었습니다
- `useWindowSize.test.ts` : test 작동예시로 작성한 코드입니다
- https://jestjs.io/
- https://testing-library.com/docs/react-testing-library/intro/
[URH-32]: https://use-react-hooks.atlassian.net/browse/URH-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[URH-32] 테스트 환경 셋팅 신규

---

src/hooks/useLocalStorage.ts

- 작업명: useLocalStorage
- 티켓: [[react hooks] useLocalStorage](https://use-react-hooks.atlassian.net/browse/URH-21?atlOrigin=eyJpIjoiZTA3ODc0NGJkMTliNDhjNDhiZDBiY2RlZGZjYTRlYjEiLCJwIjoiaiJ9)
- 상태: 신규
- 로컬 스토리지를 쉽게 사용하도록 하는 hook
- key값을 받아서 해당 key에 저장되어 있는 value와 data를 해당 key에 저장하는 setter 함수를 리턴
- 서로 다른 타입의 값 처리시 경고 문구 활성
- 변경 사항 없음
```ts
import React from 'react';
import useLocalStorage from './hooks/useLocalStorage';
// 'count' 키와 초기 값 0을 사용하여 로컬 스토리지에 저장된 값을 관리
const [count, setCount] = useLocalStorage<number>('count', 0);
const increment = () => {
setCount((prevCount) => prevCount + 1);
};
// 잘못된 타입의 값을 설정하려는 함수 (타입 에러 발생 예시)
const wrong = () => {
/**
* Failed to set item in localStorage MatchError:
* New value type does not match stored value type
* current:20 + …
```

[URH-21] useLocalStorage 신규

---

package-lock.json
package.json
src/context/ConfirmContext.tsx
src/hooks/useConfirm.ts

- 작업명: useConfirm
- 티켓: [[react hooks] useConfirm](https://use-react-hooks.atlassian.net/browse/URH-23)
- 상태: 신규
- 브라우저 `confirm()` 메서드와 동일한 기능을 제공하는 훅
- async/await 비동기 로직으로 작동
- `message`, `isOpen`, `confirm`, `onConfirm`, `onCancel`를 외부에 제공
- 변경 사항 없음
```jsx
// main.tsx
<ConfirmProvider>
<App />
</ConfirmProvider>
```
```jsx
// App.tsx
const { confirm, isOpen, message, onConfirm, onCancel } = useConfirm();
const handleConfirm = async () => {
if (await confirm('message')) {
console.log('Confirmed');
} else {
console.log('Canceled');
}
};
return (
<>
<Button onClick={handleConfirm}>Confirm</Button>
<Dialog open={isOpen}>
<DialogContent>
{message}
<Button onClick={onConfirm}>Confirm</Button>
<Button onClick={onCancel}>Cancel</Button>
</DialogContent>
</Dialog>
</>
)
}
``` …

[URH-23] useConfirm 신규

---

src/hooks/useInterval.test.ts
src/hooks/useInterval.ts
src/types/index.ts

- 티켓: [useInterval 신규](https://use-react-hooks.atlassian.net/browse/URH-15)
- 상태: 신규
- 지정된 시간 간격으로 콜백 함수를 호출하는 타이머를 설정합니다.
- `ms` 값이 변경될 때마다 interval이 재설정되며, 컴포넌트가 언마운트될 때 자동으로 타이머가 정리됩니다.
- 반환된 `clear` 함수를 호출하여 수동으로 타이머를 중지할 수도 있습니다.
- 없음
```ts
const [count, setCount] = useState(0)
const [delay, setDelay] = useState(1000)
const clear = useInterval(() => {
setCount(count + 1);
}, delay);
const handleStop = () => {
clear()    
}
const handleDelay = ({target}) => {
setDelay(target.value)
}
return (
<div>
<input type="number" value={delay} onChange={handleDelay} />
<button onClick={handleStop}>stop</button>
<div>
{count}
</div>
</div>
);
}
```
- 없음

 [URH-15] useInterval 신규 

---

src/hooks/useHover.test.tsx
src/hooks/useHover.ts

- 티켓: [useHover 신규](https://use-react-hooks.atlassian.net/browse/URH-26)
- 상태: 신규
- target 요소에 할당할 ref와 hovered 여부를 반환합니다.
- 없음
```jsx
const Component = () => {
const [ref, isHovered] = useHover();
return (
<div ref={ref} style={{ background: isHovered ? '#f00' : '#fff' }}>
{isHovered ? 'Hovered!' : 'Not Hovered'}
</div>
);
};
```

[URH-26] useHover 신규

---

src/hooks/useAsyncTasks.ts
src/hooks/useTimer.test.tsx
src/hooks/useTimer.ts
src/utils/delayExecution.test.ts
src/utils/delayExecution.ts
src/utils/index.ts

- 티켓: [useTimer 신규](https://use-react-hooks.atlassian.net/jira/software/projects/URH/list?selectedIssue=URH-14)
- 상태: 신규
- timer 기능을 지원하는 hook
- 전달된 콜백에 대한 시작과 취소기능
- 변경 사항 없음
```ts
const Component = () => {
const [count, setCount] = useState(0);
const { start, cancel } = useTimer(() => {
setCount(1234);
}, delay);
return (
<div>
<p aria-label="count-display">{count}</p>
<button onClick={start}>start</button>
<button onClick={cancel}>cancel</button>
</div>
);
};
```
- 없음

[URH-14] useTimer 신규

---

src/hooks/useOutsideInteraction.ts

- 작업명:
- 티켓: [useOnClickOutside](https://use-react-hooks.atlassian.net/browse/URH-22)
- 상태: 신규
- 특정 엘리먼트의 외부 영역을 터치, 클릭하는 경우 인자로 전달받은 함수 실행
- 키보드 사용자를 위한 접근성 개선 - 모달에 주로 사용되는 hook이기 때문에 좋은 스펙이라고 생각하여 추가
- esc 키 클릭 시 인자로 전달받은 함수 실행
- 이벤트 타입이 click 뿐만 아니라 다른 타입들도 추가되며 이름을 useOutsideInteraction으로 변경
- 키보드 이벤트(esc)도 받아 처리하도록 수정
```ts
const Modal = () => {
const [isOpen, setIsOpen] = useState(false);
const handleOutsideInteraction = () => {
setIsOpen(false);
};
const modalRef = useOutsideInteraction({ handleOutsideInteraction });
return (
<div>
<button onClick={() => setIsOpen(true)}>modal open</button>
{isOpen && (
<div ref={modalRef}>
<h2>모달</h2>
<p>모달 외부를 클릭하거나 esc키를 누르면 modal close</p>
</div>
)}
</div>
);
};
```
- 
-

[URH-22] useOutsideInteraction 신규

---

src/hooks/useDetectInactivity.test.ts
src/hooks/useDetectInactivity.ts
src/hooks/useMousePosition.ts
src/types/index.ts
src/utils/index.ts
src/utils/isClient.ts
src/utils/isTouchDevice.ts
src/utils/throttle.ts

- 티켓: [useDetectInactivity 신규](https://use-react-hooks.atlassian.net/browse/URH-42?atlOrigin=eyJpIjoiNTEwNjAzZTA1MWMwNDY3MWE0ZmRmYzIzMzA5N2RjNzEiLCJwIjoiaiJ9)
- 상태: 신규
- 지정한 시간(ms) 동안 활동이 없을 때 전달한 콜백 함수를 실행하는 훅
- 설정할 수 있는 시간은 최소 5000ms 이상(EventListener 감지 주기= 5000ms)
- 사용자의 디바이스가 터치 기능을 지원하는지를 판단(isTouchDevice)하여 이벤트 리스너를 설정
- (선택) 반환값으로 비활성상태를 나타내는 boolean값을 받을 수 있음
- useMousePosition에서 사용된 throttle을 utils로 분리 및 index.ts에 추가
- 임의의 설정시간 5분
```ts
function Component() {
function noActivity() {
alert('지정된 시간 동안 사용자의 움직임이 감지되지 않았습니다 ');
}
useDetectInactivity(300000, noActivity);
}
export default Component;
```
- 임의의 설정시간 5분
```ts
function Component() {
function noActivity() {
alert('지정된 시간 동안 사용자의 움직임이 감지되지 않았습니다 ');
}
const isInactivity = useDetectInactivity(300000, noActivity);
return …
```

[URH-42] useDetectInactivity 신규

---

src/hooks/useDebounce.test.ts
src/hooks/useDebounce.ts
src/types/index.ts

- 티켓: [useDebounce 신규](https://use-react-hooks.atlassian.net/browse/URH-43)
- 상태: 신규
- `useDebounce` 훅은 주어진 콜백 함수가 일정 시간(`delay`) 동안 호출되지 않을 때까지 콜백 함수의 실행을 지연시킵니다.
- 없음
```ts
const [searchText, setSearchText] = useState('');
const [debouncedText, setDebouncedText] = useState(searchText);
const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
const newValue = e.target.value;
setSearchText(newValue);
debounceSearchText(newValue);
};
const debounceSearchText = useDebounce((text: string) => {
setDebouncedText(text);
}, 200);
const filteredUsers = users.filter((u) =>
u.name.toLowerCase().includes(debouncedText.toLowerCase())
);
return (
<div>
<input type="text" value={searchText} onChange={handleChange} />
<ul>
{filteredUsers.map((u) => (
<li key={u.id}>{u.name}</li>
))} …
```

[URH-43] useDebounce 신규

---

src/hooks/useSound.test.ts
src/hooks/useSound.ts

- 티켓: [useSound 신규](https://use-react-hooks.atlassian.net/browse/URH-19)
- 상태: 신규
- 오디오를 관리해주는 Hook
- play, pause, stop, 반복 재생 설정, 재생 위치 설정, 볼륨 설정, 배속 설정 함수 리턴
- 오디오가 준비되었는지, 현재 볼륨, 반복 재생인지, 일시 정지 여부, 재생 여부, 오디오 길이, 현재 재생 위치 리턴
```ts
import useSound from './hooks/useSound';
const App = () => {
const result = useSound({
url: 'https://github.com/rafaelreis-hotmart/Audio-Sample-files/raw/master/sample.mp3',
});
const {
volume,
playbackRate,
isLoop,
duration,
currentTime,
play,
pause,
stop,
setIsLoop,
setPosition,
setVolume,
setPlaybackRate,
} = result;
const handleVolumeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
setVolume(parseFloat(e.target.value));
};
const handlePlaybackRateChange = (e: React.ChangeEvent<HTMLInputElement>) => {
setPlaybackRate(parseFloat(e.target.value));
}; …
```

[URH-19] useSound 신규

---

src/hooks/useScrollY.test.ts
src/hooks/useScrollY.ts
src/utils/debounce.ts

- 티켓: [useScrollY 신규](https://use-react-hooks.atlassian.net/browse/URH-24)
- 상태: 신규
- 현재 페이지(pathname)의 세로 스크롤 값을 로컬 스토리지에 저장하는 훅
- 다른 페이지로 이동했다가 다시 돌아왔을 때 `trigger()` 함수를 실행시켜 저장된 스크롤 위치로 이동할 수 있음
- 없음
```jsx
const { moveTrigger } = useScrollY();
useEffect(() => {
moveTrigger();
}, []);
return (
<div>
<h1>USE-REACT-HOOKS</h1>
</div>
);
}
export default App;
```

[URH-24] useScrollY 신규

---

src/hooks/useLongPress.test.ts
src/hooks/useLongPress.ts

- 티켓: [useLongPress 신규](https://use-react-hooks.atlassian.net/browse/URH-18)
- 상태: 신규
- 사용자가 요소를 길게 눌렀을 때 콜백 함수를 호출하는 훅
- 마우스, 터치 이벤트 지원
- 없음
```tsx
const [isLongPressed, setLongPressed] = useState(false);
const attrs = useLongPress(() => {
setLongPressed(true);
});
return (
<div>
<h1>{isLongPressed ? '✨ LONG PRESS ✨' : 'USE-REACT-HOOKS'}</h1>
<button {...attrs}>PRESS</button>
<button onClick={() => setLongPressed(false)}>RESET</button>
</div>
);
}
```

[URH-18] useLongPress 신규

---

jest.config.ts
package-lock.json
package.json
src/hooks/useClipboard.test.ts
src/hooks/useClipboard.ts
src/utils/imgToBlob.ts
src/utils/index.ts

- 티켓: [useClipboard 신규](https://use-react-hooks.atlassian.net/browse/URH-51)
- 상태: 신규 (+테스트 코드 작성 중)
- 텍스트와 이미지를 클립보드에 복사하는 훅
- 복사된 상태를 제공하여 토스트 팝업과 함께 사용할 때 유용
- 없음
```tsx
const { copied, copyText, copyImg } = useClipboard();
return (
<div>
<button 
onClick={() => copyText('Hello World')}>
Copy Text
</button>
<button
onClick={() => copyImg('https://avatars.githubusercontent.com/u/173591906?s=200&v=4')}>
Copy Image
</button>
<p> {copied ? 'Copied!' : ''}</p>
</div>
);
```
- [MDN Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)

[URH-51] useClipboard 신규

---

jest.config.ts
src/hooks/useLocalStorage.ts
src/hooks/useWorker.test.tsx
src/hooks/useWorker.ts
src/mocks/mockWorker.ts
src/types/index.ts
src/utils/index.ts
src/utils/validators.test.ts
src/utils/validators.ts

- 티켓: [useWorker 신규](https://use-react-hooks.atlassian.net/browse/URH-39?atlOrigin=eyJpIjoiMTQwYjZmYTRlZDFmNDY0ZTk0YWY4Y2I2ZjY5MzE0MmQiLCJwIjoiaiJ9)
- 상태: 신규
- 메인 스레드(주 스레드)와는 별도의 스레드에서 자바스크립트 코드를 실행하여 작업을 수행하고, 
메인 스레드가 UI 렌더링과 같은 다른 작업을 차질 없이 진행할 수 있도록 도와줍니다.
- 기본적인 작업 외에 네트워크 요청도 워커 스레드 내부에서 동작이 가능하도록 구현하였습니다.
- 유틸 함수가 분리되었습니다.
```ts
import { useEffect, useState } from 'react';
import useWorker from './hooks/useWorker';
const App = () => {
const [count, setCount] = useState(0);
return (
<div>
<h1>O(n^2) 100억 연산 블로킹 테스트</h1>
<h1>메인 스레드 비블로킹 작업 (Web Worker 사용)</h1>
<WorkerComponent />
<h1>메인 스레드 블로킹 작업 (Web Worker 미사용)</h1>
<SynchronousComponent />
<button
onClick={() =>
setCount((prev) => prev + 1)
}>{`나를 클릭해주세요!: ${count}`}</button>
</div>
);
};
const size = 100_000;
// 테스트용 O(n^2) 작업 …
```

[URH-39] useWorker 신규

---

src/hooks/useScrollLock.test.ts
src/hooks/useScrollLock.ts

- 티켓: [useScrollLock 신규](https://use-react-hooks.atlassian.net/browse/URH-49?atlOrigin=eyJpIjoiZDBlYjFlZTU3YzZhNDhiOTk1ZDAzMjA3ZmU1MDUyNWIiLCJwIjoiaiJ9)
- 상태: 신규
- 페이지의 스크롤을 잠그거나 해제하여 사용자가 스크롤할 수 없도록 하는 훅
- scroll바가 존재하여 UI형태는 유지되지만 비활성화된 형태
- 없음
- boolean 값으로 scrollLock 여부를 처리합니다
```tsx
const App = () => {
const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
useScrollLock(isModalOpen);
const openModal = () => {
setIsModalOpen(true);
};
const closeModal = () => {
setIsModalOpen(false);
};
return (
<div style={styles.container}>
{isModalOpen && (
<div style={styles.modal}>
<div style={styles.modalContent}>
...
</div>
);
};
```
위 예시처럼 isOpen과 같이 modal이 열리고 닫히는 경우 등에 해당 boolean값을 넣으면 scollLock 처리가 됨
https://github.com/user-attachments/assets/24ef48c9-40fe-450f-9c8d-ad6497c23705
- …

[URH-49] useScrollLock 신규

---

src/hooks/useGeolocation.test.ts
src/hooks/useGeolocation.ts

- 티켓: [useGeolocation 신규](https://use-react-hooks.atlassian.net/browse/URH-48)
- 상태: 신규
- 현재 유저의 [지리적 위치](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPosition) 값 리턴, 위치 불러오기 중인지 로딩 여부, 에러값 리턴
- device 위치가 변경될 때마다 호출되도록 watchPosition() 사용
```ts
const { coords, timestamp, error, loading } = useGeolocation();
if(loading){
return <p>loading...</p>
}
if(error){
return <p>{error.message}</p>
}
return (
<div>
<p>Latitude: {coords.latitude}</p>
<p>Longitude: {coords.longitude}</p>
<p>Altitude: {coords.altitude}</p>
<p>Timestamp: {new Date(timestamp).toLocaleString()}</p>
</div>
);
```
- https://developer.mozilla.org/en-US/docs/Web/API/Geolocation

[URH-48] useGeolocation 신규

---

src/hooks/useEventListener.test.tsx
src/hooks/useEventListener.ts

- 티켓: [useEventListener 신규](https://use-react-hooks.atlassian.net/browse/URH-50?atlOrigin=eyJpIjoiMzU0MmQ3MTIxYjA2NDEwOGFiNGE1MzRkN2FhM2ZiNGIiLCJwIjoiaiJ9)
- 상태: 신규
- 특정 이벤트를 지정된 Element에 등록하고, 해당 이벤트가 발생할 때 지정된 callback을 호출하는 커스텀 훅
- 이벤트 리스너를 간편하게 관리할 수 있음
- 없음
```ts
import { useRef } from 'react';
import useEventListener from './hooks/useEventListener';
const buttonRef = useRef<HTMLButtonElement>(null);
const handleClick = () => {
console.log('Button clicked!');
};
// RefObject에 대해 click이벤트를 설정
useEventListener("click", handleClick, buttonRef);
return (
<div>
<button ref={buttonRef}>Click</button>
</div>
);
}
export default App;
```
1. 기본 window에 바로 설정
2. HTMLElement에 설정
3. EventListener 기본 option 활용(capture/once/passive)
```ts
import useEventListener from …
```

[URH-50] useEventListener 신규

---

src/hooks/useOnlineStatus.test.ts
src/hooks/useOnlineStatus.ts
src/utils/index.ts
src/utils/isClient.ts

- 티켓: [useOnlineStatus 신규](https://use-react-hooks.atlassian.net/browse/URH-58)
- 상태: 신규
- 브라우저의 온라인/오프라인 상태를 판별하는 훅입니다.
- 온라인 상태가 변경될 때 실행할 콜백 함수를 선택적으로 지정할 수 있습니다.
- 없음
1. 콜백이 필요 없는 경우
```tsx
import useOnlineStatus from './hooks/useOnlineStatus';
const { isOnline } = useOnlineStatus();
return (
<div>
<h1>{isOnline ? 'online' : 'offline'}</h1>
</div>
);
}
```
2. 콜백이 필요한 경우
```tsx
const { isOnline } = useOnlineStatus({ onlineCallback, offlineCallback });
function onlineCallback() {
console.log('online');
}
function offlineCallback() {
console.log('offline');
}
return (
<div>
<h1>{isOnline ? 'online' : 'offline'}</h1>
</div>
);
}
```
- https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine
-

[URH-58] useOnlineStatus 신규

---

src/hooks/usePrefersColorScheme.ts

- 티켓: [usePrefersColorScheme 신규](https://use-react-hooks.atlassian.net/browse/URH-61)
- 상태: 신규
- 사용자의 운영 체제의 색상 설정을 감지하는 훅
- 다크모드일때는 'dark', 라이트모드일때는 'light'를 리턴
```ts
import usePrefersColorScheme from './hooks/usePrefersColorScheme';
const colorScheme = usePrefersColorScheme();
console.log('dark mode', colorScheme === 'dark');
return (
<div>
<h1>USE-REACT-HOOKS</h1>
</div>
);
}
export default App;
```
- https://ko.react.dev/reference/react/useSyncExternalStore
- https://developer.mozilla.org/ko/docs/Web/API/Window/matchMedia

[URH-61] usePrefersColorScheme 신규

---

src/hooks/useKeyCombination.test.ts
src/hooks/useKeyCombination.ts

- 티켓: [useKeyCombination 신규](https://use-react-hooks.atlassian.net/browse/URH-55)
- 상태: 신규 ~~(테스트 코드는 아직 작성 중입니다!)~~ 
- 지정된 키 조합이 눌렸을 때 콜백 함수를 호출하는 훅
- 없음
```ts
import { useCallback, useRef, useState } from 'react';
import useKeyCombination from './hooks/useKeyCombination';
const [bold, setBold] = useState(false);
const [isSave, setIsSave] = useState(false);
const input = useRef<HTMLInputElement>(null);
const toggleBold = useCallback(() => {
setBold((state) => !state);
}, [setBold]);
const keyActions = {
toggleBold: {
shortcutKeys: ['ControlLeft', 'KeyB'],
callback: toggleBold,
},
save: {
shortcutKeys: ['MetaLeft', 'KeyS'],
callback: useCallback(() => setIsSave((state) => !state), [setIsSave]),
isPrevent: true,
},
search: {
shortcutKeys: ['MetaLeft', 'KeyK'],
callback: …
```

[URH-55 ] useKeyCombination 신규

---

src/context/TranslationContext.tsx
src/hooks/useTranslation.test.tsx
src/hooks/useTranslation.ts

- 티켓: [useTranslation 신규](https://use-react-hooks.atlassian.net/browse/URH-59)
- 상태: 신규
- 기능 : 사용자가 설정한 언어에 따라 텍스트를 변경해줌
- changeLanguage 함수를 사용해 언어 변경 가능
- useTranslation에서 리턴 받은 t 함수를 통해 언어 리소스에서 번역된 텍스트를 가져올 수 있음 
```ts
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import { TranslationProvider } from './context/TranslationContext';
const translations = {
en: {
greeting: 'Hello ${name}, You have ${count} new messages.',
farewell: 'Goodbye ${name}',
},
ko: {
greeting: '안녕하세요 ${name}, 새 메시지가 ${count}개 있습니다.',
farewell: '안녕히 가세요 ${name}',
},
};
ReactDOM.createRoot(document.getElementById('root')!).render(
<TranslationProvider translations={translations} defaultLanguage="en">
<App />{' '}
</TranslationProvider>
);
```
- useTranslation을 사용하는 곳 상위 컴포넌트에서 …

[URH-59] useTranslation 신규

---

package-lock.json
package.json
src/hooks/useDeepCompareEffect.ts

- 티켓: [useDeepCompareEffect 신규](https://use-react-hooks.atlassian.net/browse/URH-57)
- 상태: 신규
- 의존성 배열의 깊은 비교를 통해 변화를 감지하고 콜백을 실행시킵니다.
- `isEqual()` 함수를 사용하기 위해 [fast-deep-equal](https://bundlephobia.com/package/fast-deep-equal@3.1.3) 패키지를 추가하였습니다.
- `isEqual()` 함수를 직접 작성하려면 상당한 양의 코드가 필요합니다.
- fast-deep-equal 패키지는 852byte의 작은 번들 사이즈와 주당 46,000,000 이상 다운로드하는 패키지로 신뢰성이 높아 설치해봤습니다.
```tsx
const [, setCount] = useState(0);
const effectCountRef = useRef(0);
const deepCompareCountRef = useRef(0);
useEffect(() => {
effectCountRef.current += 1;
// 빈 객체는 매번 새로운 참조를 갖기 때문에 effectCount는 계속 증가
}, [{}]);
useDeepCompareEffect(() => {
deepCompareCountRef.current += 1;
// 빈 객체를 같은 값으로 판단해 deepCompareCountRef는 한 번(첫 시도)만 증가
}, [{}]);
return (
<div>
<p>effectCount: …
```

[URH-57] useDeepCompareEffect 신규

---

src/hooks/usePreventCopy.test.ts
src/hooks/usePreventCopy.ts

- 티켓: [usePreventCopy 신규](https://use-react-hooks.atlassian.net/browse/URH-67)
- 상태: 신규
- 브라우저에서 복사 이벤트 발생 시 이벤트를 차단하고 콜백 함수를 실행합니다.
없음
```tsx
const callbackCopy = () => {
alert('복사할 수 없습니다.');
};
usePreventCopy(callbackCopy);
return (
<div>
<h1>USE-REACT-HOOKS</h1>
</div>
);
}
```

[URH-67] usePreventCopy 신규

---

src/hooks/usePermission.test.tsx
src/hooks/usePermission.ts

- 티켓: [usePermission 신규](https://use-react-hooks.atlassian.net/jira/software/projects/URH/list?direction=DESC&selectedIssue=URH-62&sortBy=assignee)
- 상태: 신규
- 사용자의 권한 상태를 확인하고 추적하는 커스텀 훅.
- 해당 사항 없음
```ts
import React, { useState } from 'react';
import usePermission from './hooks/usePermission';
const LocationComponent: React.FC = () => {
const { status } = usePermission({ permission: 'geolocation' });
const [location, setLocation] = useState<{
latitude: number;
longitude: number;
} | null>(null);
const handleGetLocation = () => {
if (status === 'prompt' || status === 'granted') {
navigator.geolocation.getCurrentPosition(
(position) => {
setLocation({
latitude: position.coords.latitude,
longitude: position.coords.longitude,
});
},
(error) => {
console.error('위치 정보를 가져오는데 실패했습니다.', error); …
```

[URH-62] usePermission 신규

---

src/hooks/useMockData.test.ts
src/hooks/useMockData.ts
src/utils/validators.test.ts
src/utils/validators.ts

- 티켓: [useMockData 신규](https://use-react-hooks.atlassian.net/browse/URH-70?atlOrigin=eyJpIjoiNTg1ZmIxZTVmYzlhNGRiZjhkMWU3MzM3NTQ1YjhkNjEiLCJwIjoiaiJ9)
- 상태: 신규
- 필요한 더미데이터를 생성해주는 훅
- 타입을 포함한 객체를 전달하면 해당 타입과 맞는 더미 데이터 반환 (중첩 지원)
- 지원하는 mock 타입: string, number, boolean, image, date, UUID, array, object
- 범위값 조정 지원 (문자열길이, 숫자길이, 이미지 너비 높이, 날짜 범위)
- 생성된 mock 객체 타입 자동완성 지원
- 없음
```ts
import React from 'react';
import useMockData from './hooks/useMockData';
const App = () => {
const { mockData, addItem } = useMockData({
schema: {
user: {
id: 'UUID',
name: 'string',
age: 'number',
address: ['string', 'string'],
profilePicture: 'image',
registrationDate: 'date',
isAdmin: 'boolean',
inventory: {
money: 'number',
connectionUser: [
{
userId: 'UUID',
name: 'string',
isActive: 'boolean',
address: …
```

[URH-70] useMockData 신규

---

docs/pages/docs/hooks/_meta.json
docs/pages/docs/hooks/useDeepCompareEffect.mdx

- 티켓: [useDeepCompareEffect 문서 신규](https://use-react-hooks.atlassian.net/browse/URH-102)
- 상태: 신규

[URH-102] useDeepCompareEffect 문서 신규

---

docs/pages/docs/hooks/_meta.json
docs/pages/docs/hooks/useInterval.mdx

- 티켓: [useInterval 문서](https://use-react-hooks.atlassian.net/browse/URH-92)
- 상태: 신규

[URH-92] useInterval 문서 신규

---

package.json

- 이슈: [docs 페이지 배포(vercel)](https://github.com/frontend-opensource-project/use-react-hooks/issues/103)
- 상태: 신규
- 배포 중 husky 명령을 실행하는 과정에서 에러가 발생했습니다.
- production 환경에서 설치되지 않은 husky를 실행함에 따라 발생한 에러였습니다.
- husky는 devDependencies입니다.
- package가 의존성으로 설치될 경우 husky를 설치하지 않게 prepare를 수정했습니다.

✨ feat: docs 페이지 배포(vercel)

---

docs/pages/hooks/_meta.json
docs/pages/hooks/useWindowSize.mdx
src/hooks/useWindowSize/useWindowSize.ts

- 이슈: [useWindowSize docs 작성](https://github.com/frontend-opensource-project/use-react-hooks/issues/100)
- 상태: 신규

[URH-100] useWindowSize docs 작성
